#!/bin/bash

getBlockHash="$2 -rpcuser=$3 -rpcpassword=$4 -rpcport=$5 getblockhash"
getBlock="$2 -rpcuser=$3 -rpcpassword=$4 -rpcport=$5 getblock"

blockCount=$($2 -rpcuser=$3 -rpcpassword=$4 -rpcport=$5 getblockcount)
blockHash=$($2 -rpcuser=$3 -rpcpassword=$4 -rpcport=$5 getbestblockhash)
blockWindow=$6

mkdir -p $1
fields=( pow_algo_id pow_algo difficulty size weight time mediantime tx )

echo $($getBlock $blockHash) > $1/best_block.json
echo $blockCount > $1/block_count.json

declare -A results

for ((i=1;i<=$blockWindow;i++))
do
	echo $i

	block=$($getBlock $blockHash)
	blockHash="${block#*previousblockhash\": \"}"
        blockHash="${blockHash%%\"*}"

	for field in "${fields[@]}"
	do
		value="${block#*$field\": }"

		if [ $field == "tx" ]; then
			value="${value%%\]*}"
			value=$(echo $value | awk -F, '{print NF-1}')
		fi

		value="${value%%,*}"

		if [ $i != "1" ]; then
			results[$field]=$value,${results[$field]}
		else
			results[$field]=$value
		fi
	done

	if [[ $i = @(100|1000|10000|25000|50000|100000) ]]; then
		echo "Reached checkpoint"
		directory=$1/$i
		mkdir -p $directory

		for field in "${fields[@]}"
		do
        		fileName=$directory/$field.json
       			echo "Writing $fileName"
 			echo "[${results[$field]}]" > $fileName
		done
	fi
done
