#!/bin/bash

getBlockHash="$2 -rpcuser=$3 -rpcpassword=$4 -rpcport=$5 getblockhash"
getBlock="$2 -rpcuser=$3 -rpcpassword=$4 -rpcport=$5 getblock"
blockCount=$($2 -rpcuser=$3 -rpcpassword=$4 -rpcport=$5 getblockcount)
blockWindow=$6
startBlock=$((blockCount - blockWindow))

mkdir -p $1
fields=( pow_algo_id pow_algo difficulty size weight time )

declare -A results

for ((i=0;i<$blockWindow;i++))
do
	blockIndex=$((startBlock + i))
	echo $blockIndex
	block=$($getBlock $($getBlockHash $blockIndex))

	for field in "${fields[@]}"
	do
		value="${block#*$field\": }"
		value="${value%%,*}"
		if [ $i != "0" ]; then
			results[$field]=${results[$field]},
		fi
		results[$field]=${results[$field]}$value
	done
done

for field in "${fields[@]}"
do
	fileName=$1/$field.json
	echo "Writing $fileName"
	echo "[${results[$field]}]" > $fileName
done
